function instructions = defineInstructions(window, phase)

% instructions for phase 1
instructions{1} = ['Welcome to the nsd post scanning behavioural task', ...
'\n You will be presented scenes one at a turn, and we will ask you a few questions.', ...
];

instructions{2} = ['\n\n Have you seen this picture before?',...
'\n\n Press 1 if you are certain you have seen it before.',...
'\n\n Press 2 if you are ? you have seen it before.',...
'\n\n Press 3 if you are ? you have seen it before.',...
'\n\n Press 4 if you are ? you have not seen it before.',...
'\n\n Press 5 if you are ? you have not seen it before.',...
'\n\n Press 6 if you are certain you have not seen it before.',...
'\n\n Press backspace to continue'];


% instructions for phase 3
instructions{3} = ['Once you responded to the first question', ...
'\n you may be asked about how often', ...
'\n\n whether you have seen the scene displayed before.',...
'\n\n Press 1 if you are certain you have seen it before.',...
'\n\n Press 2 if you are ? you have seen it before.',...
'\n\n Press 3 if you are ? you have seen it before.',...
'\n\n Press 4 if you are ? you have not seen it before.',...
'\n\n Press 5 if you are ? you have not seen it before.',...
'\n\n Press 6 if you are certain you have not seen it before.',...
'\n\n Press backspace to continue'];

% instructions for phase 3
instructions{4} = ['Welcome to the nsd post scanning behavioural task', ...
'\n To begin, you will see a series of scenes, and have to indicate', ...
'\n\n whether you have seen the scene displayed before.',...
'\n\n Press 1 if you are certain you have seen it before.',...
'\n\n Press 2 if you are ? you have seen it before.',...
'\n\n Press 3 if you are ? you have seen it before.',...
'\n\n Press 4 if you are ? you have not seen it before.',...
'\n\n Press 5 if you are ? you have not seen it before.',...
'\n\n Press 6 if you are certain you have not seen it before.',...
'\n\n Press backspace to continue'];

% display the right instructions according to the phase
